services:
  apache:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: CryptoTrade_apache
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/apache2/apache.conf:/etc/apache2/sites-available/000-default.conf
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    env_file:
      - ./app/.env
    depends_on:
      - mysql
    networks:
      - cryptoTrade_network

  mysql:
    image: mysql:8.0
    container_name: CryptoTrade_mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: crypto_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql            # Persistent DB data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  # Auto-run script
    networks:
      - cryptoTrade_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: labo4_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootpassword
    depends_on:
      - mysql
    networks:
      - cryptoTrade_network

  market-simulator:
    build:
      context: .
      dockerfile: daemon/Dockerfile
    container_name: CryptoTrade_market_simulator
    volumes:
      - ./app:/app
    depends_on:
      - mysql
    networks:
      - cryptoTrade_network
    restart: unless-stopped

networks:
  cryptoTrade_network:
    driver: bridge

volumes:
  mysql_data:
